### ISSUE TITLE
"No API Key / Token found. Please re-login!"

### ISSUE THREAD

**Issue by mikebell** [bimovidia/planning-poker#11]
I'm trying to set this up on a server and I get the following error "No API Key / Token found. Please re-login!"

My user has a token in pivotal which is being used already for github integration.

Looking through the code I it's coming from the RestClient::Unauthorized. What is calling this? Am I missing a configuration step?

**Comment by bimovidia** [comment]
There should not be any configuration step needed with planning-poker app. It currently uses the `pivotal-tracker` gem (https://github.com/jsmestad/pivotal-tracker), so you might want to read up their documentation.

**Comment by bimovidia** [comment]
While upgrading the app to Rails 4.2.5.1, I've found the issue. 
It should be fixed now.
