### ISSUE TITLE
Unestimated Button Not Working

### ISSUE THREAD

**Issue by tpitman** [bimovidia/planning-poker#7]
When I click on the UNESTIMATED button nothing happens. I watch the server and there is not log output.

I would expect when I hit it that it would filter the page down to just unestimated items.

My project has a bunch of stories and many are unestimated and many are estimated.

**Comment by oldcookie** [comment]
Ran into the same problem.  Probably an issue with Faye not accessible.  Just need to make sure you configure FAYE_URL env var to the actual host:port

**Comment by bimovidia** [comment]
Closing for now
