### ISSUE TITLE
Reveal Does Nothing

### ISSUE THREAD

**Issue by tpitman** [bimovidia/planning-poker#8]
It is me again. I am wondering if there is some related problem with the other issue I reported.

I connect to the server and log in. It shows my projects. I pick one. I open an unestimated story and click on my estimate. The reveal button is still not showing.

I tried having another dev also log in with his account and pick the same story just to see if at least 2 people had to be voting. Still nothing. I hit save and nothing happens either.

Any ideas?

**Comment by bimovidia** [comment]
Closing for now
